### ISSUE TITLE
[BUG] Filter lists don't show or update at all

### ISSUE THREAD

**Issue by Daniel9132** [SEVENNetworks/AdClearContentBlocker#12]
**Describe the bug**
When I try to open the filter lists there is an error Message saying "an error occurred, please try again later" and the page is blank.

**To Reproduce**
1. Go to 'adclear app'
2. Click on 'open filters'
3. See error

**Expected behavior**
Open the filter lists

**Screenshots**
![Screenshot_20230527_111645_AdClear Content Blocker](https://github.com/SEVENNetworks/AdClearContentBlocker/assets/33548848/21a2fc40-da71-4d49-9f67-85fa3c4f9d00)

**Device Info (please complete the following information):**
 - Device: S20 FE 5G
 - OS: Android 13
 - App: adclear
 - Version 3.4.2.330-galaxy

**Comment by DustinMorgan** [comment]
Hi @Daniel9132,

Thanks for bringing this to our attention! We've started investigating the bug you've reported. We'll make sure to keep you posted with any updates. If you come across any more information that might help, please share it.

**Comment by DustinMorgan** [comment]
This should now be resolved. Please let us know if you have any additional issues.
